Acme\FeedbackBundle\Entity\Questions:
    type: entity
    table: questions
    indexes:
        page:
            columns:
                - page
    id:
        idQuestion:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id_question
            generator:
                strategy: IDENTITY
    fields:
        questionName:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: question_name
        questionType:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: question_type
        isRequired:
            type: boolean
            nullable: false
            comment: ''
            column: is_required
        page:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        createdAt:
            type: datetime
            nullable: false
            comment: ''
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            comment: ''
            column: updated_at
        deleted:
            type: boolean
            nullable: false
            comment: ''
            default: '0'
    lifecycleCallbacks: {  }
