acme_authenticate:
    pattern:  /authenticate/
    defaults: { _controller: AcmeFeedbackBundle:Default:authenticate}
    
acme_feedback:
    pattern:  /feedback/{page}
    defaults: { _controller: AcmeFeedbackBundle:Default:index, page: 1 }
    requirements:
        page:  \d+

acme_target_route:
    pattern:  /order/
    defaults: { _controller: AcmeFeedbackBundle:Default:order}
    
acme_thankyou:
    pattern:  /thankyou/
    defaults: { _controller: AcmeFeedbackBundle:Default:thanku}
